import { Reducer } from 'redux';
import { Tile, getNextTile, isBoardFilled as isBoardFilledRule } from '../board';
import { isActionToggleTile } from './actions';

const { RED, BLUE } = Tile;

export interface ReducerState {
	width: number;
	height: number;
	locked: Array<Tile | null>;
	player: Array<Tile | null>;
}

export const DEFAULT_STATE: ReducerState = {
	width: 4,
	height: 4,
	locked: [
		null, null, BLUE, RED,
		BLUE, null, null, null,
		null, BLUE, BLUE, null,
		null, null, null, null,
	],
	player: [
		null, null, null, null,
		null, null, null, null,
		RED, null, null, RED,
		null, null, null, null,
	],
};

const reducer: Reducer<ReducerState> = (state = DEFAULT_STATE, action) => {
	if (isActionToggleTile(action)) {
		const { x, y } = action.data;
		const index = getTileIndex(state, x, y);
		const tile = getPlayerTile(state, x, y);
		const nextTile = getNextTile(tile);
		const player = [...state.player];
		player[index] = nextTile;
		return {
			...state,
			player,
		};
	}

	return state;
};

export default reducer;

export const getBoardWidth = (state: ReducerState) => (
	state.width
);

export const getBoardHeight = (state: ReducerState) => (
	state.height
);

/** Convert (x, y) coordinates to a tile index (between `0` and `x * y`). */
const getTileIndex = (state: ReducerState, x: number, y: number) => (
	state.width * y + x
);

/** Returns the total number of tiles for the board. */
const getTileCount = (state: ReducerState) => (
	state.width * state.height
);

/** Get the tile as it was generated by the game by index. */
const getLockedTileByIndex = (state: ReducerState, index: number) => (
	state.locked[index]
);

/** Get the tile as it was generated by the game by (x, y) coords. */
export const getLockedTile = (state: ReducerState, x: number, y: number) => (
	getLockedTileByIndex(
		state,
		getTileIndex(state, x, y)
	)
);

/** Get the tile as it has been entered by the player by index. */
const getPlayerTileByIndex = (state: ReducerState, index: number) => (
	state.player[index]
);

/** Get the tile as it has been entered by the player by (x, y) coords. */
export const getPlayerTile = (state: ReducerState, x: number, y: number) => (
	getPlayerTileByIndex(
		state,
		getTileIndex(state, x, y)
	)
);

/** Get the tile as it was generated or has been entered by index. */
const getDisplayTileByIndex = (state: ReducerState, index: number) => (
	getLockedTileByIndex(state, index) ||
	getPlayerTileByIndex(state, index)
);

/** Get the tile as it was generated or has been entered by (x, y) coords. */
export const getDisplayTile = (state: ReducerState, x: number, y: number) => (
	getDisplayTileByIndex(
		state,
		getTileIndex(state, x, y)
	)
);

/** Returns a merged set of locked and player tiles. */
const getDisplayTiles = (state: ReducerState) => {
	const result = [];
	const length = getTileCount(state);
	for (let i = 0; i < length; i++) {
		result.push(
			getDisplayTileByIndex(state, i)
		);
	}
	return result;
};

/** Returns `true` if the tile is locked and cannot be changed by the player. */
export const isTileLocked = (state: ReducerState, x: number, y: number) => (
	getLockedTile(state, x, y) !== null
);

/** Returns `true` if no positions on the board are empty. */
export const isBoardFilled = (state: ReducerState) => {
	const tiles = getDisplayTiles(state);
	return isBoardFilledRule(tiles);
};
